# Generated by Django 3.2.6 on 2021-11-21 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnfAuditivas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enfermedades',
            options={'verbose_name': 'Enfermedad', 'verbose_name_plural': 'Enfermedades'},
        ),
    ]
